--- 
version: '3.2'
services:
 zookeeper:
   image: confluentinc/cp-zookeeper:latest
   container_name: zookeeper
   environment:
     - ZOOKEEPER_CLIENT_PORT=2181
   ports:
     - 2181:2181
   volumes:
     - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
     - "./volumes/zookeeper/logs:/var/lib/zookeeper/log"
   networks:
     - sdh_nw

 kafka:
   image: confluentinc/cp-kafka:latest
   container_name: kafka
   environment:
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
     - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:19092,EXTERNAL://${MY_IP}:9092
     - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL    
     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
     - KAFKA_MESSAGE_MAX_BYTES=1000012
   ports:
     - 9092:9092
     - 19092:19092
   depends_on:
     - zookeeper
   volumes:
     - "./volumes/kafka/data:/var/lib/kafka/data"
     - "./volumes/kafka/logs:/var/lib/kafka/logs"
   networks:
     - sdh_nw

 schema-registry:
   image: confluentinc/cp-schema-registry:latest
   container_name: schema-registry
   environment:
     - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:19092
     - SCHEMA_REGISTRY_HOST_NAME=schema-registry
     - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
   ports:
     - 8081:8081
   depends_on:
     - zookeeper
     - kafka
   networks:
     - sdh_nw

 kafka-rest:
   image: confluentinc/cp-kafka-rest:latest
   container_name: kafka-rest
   environment:
     - KAFKA_REST_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:19092
     - KAFKA_REST_LISTENERS=http://0.0.0.0:8082
     - KAFKA_REST_SCHEMA_REGISTRY_URL=http://schema-registry:8081
     - KAFKA_REST_HOST_NAME=kafka-rest
   ports:
     - 8082:8082
   depends_on:
     - zookeeper
     - schema-registry
   networks:
     - sdh_nw

 kafka-topic-ui:
  image: landoop/kafka-topics-ui
  container_name: kafka-topics-ui
  ports:
    - 8001:8000
  environment:
    - KAFKA_REST_PROXY_URL=http://kafka-rest:8082
    - PROXY=true
  depends_on:
    - kafka
    - kafka-rest
  networks:
    - sdh_nw

 rest_streamer:
    #image: 471108701394.dkr.ecr.us-east-1.amazonaws.com/arln/translation-rest-streamer:db862b91
   image: simple_rest-streamer
    container_name: simple_rest_streamer
    environment:
      - KAFKA_BOOTSTRAP_SERVER=http://kafka:9092
    depends_on:
      - kafka
    networks:
      - sdh_nw



networks:
 sdh_nw:
   driver: bridge
#   external:
#      name: sdh_nw
