--- 
version: '3.2'
services:
 zookeeper:
   image: confluentinc/cp-zookeeper:latest
   container_name: zookeeper
   environment:
     - ZOOKEEPER_CLIENT_PORT=2181
   ports:
     - 2181:2181
   volumes:
     - "./volumes/zookeeper/data:/var/lib/zookeeper/data"
     - "./volumes/zookeeper/logs:/var/lib/zookeeper/log"
   networks:
     - sdh_nw

 kafka:
   image: confluentinc/cp-kafka:latest
   container_name: kafka
   environment:
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092
     - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
     - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:19092,EXTERNAL://192.168.86.195:9092
     - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL    
     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
   ports:
     - 9092:9092
     - 19092:19092
   depends_on:
     - zookeeper
   volumes:
     - "./volumes/kafka/data:/var/lib/kafka/data"
     - "./volumes/kafka/logs:/var/lib/kafka/logs"
   networks:
     - sdh_nw

 rest_streamer:
  #image: 471108701394.dkr.ecr.us-east-1.amazonaws.com/arln/translation-rest-streamer:db862b91
  image: simple_rest-streamer
  container_name: simple_rest_streamer
  environment:
    - KAFKA_BOOTSTRAP_SERVERS=http://kafka:9092
    - app_serviceurl=http://a6a033b64485d11ea90ef02a63d31329-125258837.us-east-1.elb.amazonaws.com/translation-service/translate/daart-gc
  depends_on:
    - kafka
  networks:
    - sdh_nw

networks:
 sdh_nw:
   driver: bridge
